name: check

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: run prettier
        uses: creyD/prettier_action@v4.6
        with:
          dry: true
          prettier_options: "--check ."